"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var string_1 = require("./string");
var number_1 = require("./number");
var cadena = new string_1.Cadena('anita lava la tina');
var voc = cadena.vocales;
console.log('Vocales de ' + cadena.cad + ': ');
console.log(voc);
console.log('Es palindromo? ' + cadena.cad + ': ' + cadena.esPalindromo);
console.log('Letras de ' + cadena.cad + ': ' + cadena.letras);
console.log('Palabras de ' + cadena.cad + ': ' + cadena.palabras);
var numero = new number_1.Numero(6);
console.log('sumar [1, 2, 3] + ' + numero.num + ' = ' + numero.sumarArray([1, 2, 3]));
console.log('sumar 4 + ' + ' ' + numero.num + ' = ' + numero.sumar(4));
console.log('restar [1, 2, 3] + ' + numero.num + ' = ' + numero.restarArray([1, 2, 3]));
console.log('restar 1 - ' + numero.num + ' = ' + numero.restar(1));
console.log('factorial de ' + numero.num + ' = ' + numero.factorial);
console.log('factorial de 3 = ' + numero.factorialNum(3));
console.log('primo: ' + numero.num + ' =  ' + numero.primo);
console.log('primo 41 = ' + numero.primoNum(41));
